### ISSUE TITLE
Add optional key for password field

### ISSUE THREAD

**Issue by opi** [YunoHost-Apps/jirafeau_ynh#10]
See https://github.com/YunoHost/admin_js/issues/64, as the password field can be empty.

**Comment by maniackcrudelis** [comment]
Salut,

je viens de faire un essai, le mot de passe vide ne fonctionne pas. Il affiche une erreur indiquant que le champs n'est pas rempli.

```Argument manquant : 'upload_password'```

**Comment by jeromelebleu** [comment]
Should be fixed by https://github.com/YunoHost/moulinette-yunohost/commit/a336f33276097e7bc2732802206c9a0b592e63c9

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/510

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
