### ISSUE TITLE
Téléchargement des fichiers public en mode privé

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/jirafeau_ynh#15]
Salut,

J'ai un manquement dans le fonctionnement de Jirafeau actuellement. En effet, soit je le laisse public et je dois m'assurer que tout les utilisateurs de mon Yunohost connaissent le mot de passe, soit je le rend privé mais je ne peux alors envoyer des fichiers qu'aux utilisateurs de mon Yunohost.

Il serait intéressant pourtant de pouvoir réserver l'upload de fichier aux utilisateurs yunohost sans mot de passe, tout en gardant la possibilité d'envoyer des fichiers à n'importe qui.

De mon côté, pour obtenir ce comportement j'utilise ces commandes:
`sudo yunohost app setting jirafeau skipped_uris -v "/"`
`sudo yunohost app setting jirafeau protected_regex -v "jirafeau/$"`
Ainsi, seule la racine de jirafeau est privé.

**Comment by matlink** [comment]
Bien vu maniack, les regex sont parfaites.

**Comment by Kloadut** [comment]
Ce serait intéressant que ce soit le comportement par défaut. Le mot de passe d'upload est stocké en clair dans Jirafeau...

**Comment by julienmalik** [comment]
Ca fait sens effectivement que ça soit le comportement par défaut.
Je sais juste pas encore comment réorganiser les params du manifest. ll faudrait simplifier tout ça, dans la situation actuelle les users comprennent déjà pas bien la combinatoire et je les comprends...

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/509

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)

**Comment by maniackcrudelis** [comment]
Fix here https://github.com/YunoHost-Apps/jirafeau_ynh/blob/48ed2dc5b80ed7f1ddd39a46917f993a8c4207d5/scripts/install#L140-L146
