### ISSUE TITLE
timed out sur gros fichiers

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/jirafeau_ynh#27]
Salut,

de la même manière que [bozon](https://github.com/YunoHost-Apps/bozon_ynh/issues/15), impossible d'uploader des "gros" fichiers.

timed out:

```
[error] 27659#0: *521443 upstream timed out (110: Connection timed out) while sending request to upstream, client: 192.168.1.151, server: crudelis.fr, request: "POST /jirafeau/script.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-jirafeau.sock"
```

Et visuellement, rien ne se passe dans un premier temps:
https://crudelis.fr/lutim/pFJq2OQU/AzESyUOi.jpeg
J'ai attendu plus d'une heure sur cette page sans résultats.

Et, en l'absence de timeout dans le log nginx, on se retrouve avec un résultat vide...
https://crudelis.fr/lutim/Aj11xEft/sMyb6tws.jpeg

Essai avec des fichiers de 2.3Go et 1.1Go.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/507

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
