### ISSUE TITLE
Upgrade 3.2.0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/jirafeau_ynh#31]
Le package est en 1.1
Je suis dessus...

**Comment by Jaxom99** [comment]
Je suis intéressé à avoir la dernière version. Merci pour le boulot !

**Comment by frju365** [comment]
Fixed with https://github.com/YunoHost-Apps/jirafeau_ynh/pull/36

**Comment by Jaxom99** [comment]
Merci ! La mise à jour s'est bien passée sur mon RPi jessie.
