### ISSUE TITLE
Don't backup data during upgrade process

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/jirafeau_ynh#41]
When backing up the app during the upgrade process, the data directory is backed-up as well, which can be veeery long for a file-sharing application.
Using same method as Nextcloud ([here](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/backup#L81-L88), [here](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/restore#L109-L119) and [here](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L54-L55)) would be recommended.

**Comment by yalh76** [comment]
https://github.com/YunoHost-Apps/jirafeau_ynh/blob/f7225b48d8b2a55d512e89861d1d89776348408d/scripts/backup#L47

As been implemented
