### ISSUE TITLE
Impossible to leave empty password

### ISSUE THREAD

**Issue by OursBlanc42** [YunoHost-Apps/jirafeau_ynh#52]
Hi there.
I m trying to instal jirafeau but impossible to leave password field empty. (To allow the permission to all user) . i have this error : Le mot de passe doit comporter au moins 8 caractères

Password must contains at least 8 characters 

Regards

**Comment by prysme01** [comment]
would be interrested also to have a no password since the user has to be registered in yunohost.

**Comment by b01xy** [comment]
yes, +1
it is also nice to let the ability to use jirafeau without any registration as it was before when you were not obliged to put a password.
if someone know how the password requirement can be removed once installed, i'd go for it

thks
b

**Comment by maniackcrudelis** [comment]
You can manually edit the file `/var/www/jirafeau/lib/config.local.php` and remove the password at the line with `upload_password` (Should be line 77)

**Comment by b01xy** [comment]
ok, thanks perfect
it gives  : $cfg['upload_password'] = array();

**Comment by pdhixenbaugh** [comment]
> Hi
> 
> since a recent upgrade of the core, it's not allowed anymore to use a weak password... Even if you want to... I'm going to open a issue for that particular case, where the password is optional.
> 
> Meanwhile, you can remove this limitation with the following command:
> 
> ```
> sudo yunohost settings set security.password.admin.strength -v -1
> sudo yunohost settings set security.password.user.strength -v -1
> ```

I get an error:
`Error: The filter key security.password.user.strength has too many sub-levels, the max is 3.`
