### ISSUE TITLE
Upload password leaked in (shared on paste.yunohost.org) debug logs

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/jirafeau_ynh#60]
Hi,

I tried to upgrade my app and met #58 (I guess). I wanted to share the logs with `yunohost log display 20190523-080114-app_upgrade-jirafeau --share` and I saw that my upload password was leaking in the past!

See: `2019-05-23 10:01:23,859: DEBUG - + upload_password='MYPASSWORD'` and at several other places.

I am not sure if this is an issue with this package or yunohost logs but I prefer to open a ticket and move it in needed than to not report it, I hope that's OK.

Thanks for the app anyway!

**Comment by maniackcrudelis** [comment]
That's indeed an issue with the app package, because the app doesn't use helpers to hide the password in its scripts.

**Comment by nicofrand** [comment]
Great, that'll be easier to fix, thanks for the info.

**Comment by nicofrand** [comment]
Which helper would that be though? I looked for something in https://yunohost.org/#/packaging_apps_helpers_en but I don't see anything related?

**Comment by kay0u** [comment]
`ynh_print_OFF` and `ynh_print_ON`

Surrounds the password with something like that:

```bash
ynh_print_OFF
upload_password=$(ynh_app_setting_get --app=$app --key=upload_password)
ynh_print_ON
```

And do this OFF/ON each time upload_password is used I think
