### ISSUE TITLE
能不能获取文件的直链？

### ISSUE THREAD

**Issue by DorisGia** [YunoHost-Apps/jirafeau_ynh#64]
反正是临时的，不会有人盗链，获取直链可以方便传个视频加个video标签给朋友在线看

如果怕生成直链被盗链，可以加个权限，管理员上传可以获取直链，普通用户没有

**Comment by chenyuu8** [comment]
If you upload an mp4, you can preview and play it on your computer, but you can't play it on the ipone.

**Comment by yalh76** [comment]
Doesn't seems to be specific to the YunoHost package
