### ISSUE TITLE
Automatically clean up expired files

### ISSUE THREAD

**Issue by spctrlth** [YunoHost-Apps/jirafeau_ynh#66]
Jirafeau doesn't automatically clean up expired files which means that an instance fills up unless you clean up manually. There is a script to automatically clean up expired files[1] which could be added as a daily cronjob during installation (or give the option during installation to have the job added).

[1] https://gitlab.com/mojo42/Jirafeau/#how-can-i-automatize-the-cleaning-of-old-expired-files

**Comment by kay0u** [comment]
closed by #70
