### ISSUE TITLE
Special character support in password

### ISSUE THREAD

**Issue by 16mhz** [YunoHost-Apps/jirafeau_ynh#7]
Hello,

During the installation of jirafeau in the web interface of Yunohost, I set a password to upload file but this password doesn't work when I want to use the app.
I watched logs of the installation and I saw my password is truncated (only the last half is used).

My password contains special characters so maybe it could be a problem.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/511

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
