### ISSUE TITLE
admin.php KO

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/jirafeau_ynh#75]
Hello, 
when trying to go on the admin page of jirafeau, 
```
Sorry, the admin interface is not enabled.
```
i posted on the forum too : https://forum.yunohost.org/t/jirafeau-admin-php-ko-apres-mis-a-jour/5327

is there any other solution to fix this without uninstall/reinstall ?

thx for your help

**Comment by kay0u** [comment]
Hi, thank you for the report.

It's related to this line: https://github.com/YunoHost-Apps/jirafeau_ynh/blob/4a5209e0b633e8684e7cbb8f572469d1abc1848b/scripts/upgrade#L21
The key should be `admin` not `admin_user`: https://github.com/YunoHost-Apps/jirafeau_ynh/blob/157fa25057fca6d2c4350c76d3bf691ffb162c2d/scripts/install#L51

I'll push an epic fix in master.

**Comment by kay0u** [comment]
Fixed by #76
